### ISSUE TITLE
Error: unknown parameter in reg_f3d

### ISSUE THREAD

**Issue by fepegar** [KCL-BMEIS/niftyreg#46]
According to the help, one can use `reg_f3d` with CUDA by specifying `-platf 1`. However, this parameter is not recognised.

```shell
$ reg_f3d -ref ../aylj_t1_post.nii.gz -flo mirror_image_left.nii.gz -res left_on_post_reg.nii.gz -platf 1
[reg_f3d] 
[reg_f3d] Command line:
[reg_f3d] 	 reg_f3d -ref ../aylj_t1_post.nii.gz -flo mirror_image_left.nii.gz -res left_on_post_reg.nii.gz -platf 1
[reg_f3d] 
[NiftyReg ERROR] 	Parameter unknown:
[NiftyReg ERROR] -platf
```

This parameter is captured by `reg_aladin`
https://github.com/KCL-BMEIS/niftyreg/blob/62dc6106481a9b47fa4c4ff60bb41ff7ce867499/reg-apps/reg_aladin.cpp#L352
but not by `reg_f3d`, despite the help message
https://github.com/KCL-BMEIS/niftyreg/blob/62dc6106481a9b47fa4c4ff60bb41ff7ce867499/reg-apps/reg_f3d.cpp#L134-L143

Can `reg_f3d` use CUDA?

**Comment by mmodat** [comment]
It cannot anymore. We will re-activate it after some large refactoring.
It should not be in the help, will remove it.
