### ISSUE TITLE
CUDA ERROR: too many resources requested for launch

### ISSUE THREAD

**Issue by wangqin4377** [KCL-BMEIS/niftyreg#49]
Hi,

When I run this command with CUDA version `reg_aladin -ref a.nii -flo b.nii -res c.nii -aff ref_template_flo_new_image_affine_matrix.txt -platf 1 -gpuid 0`

I got this error:
`
NiftyReg CUDA ERROR] file '/home/qinwang/nifty/niftyreg-git/reg-lib/cuda/resampleKernel.cu' in line 443 : too many resources requested for launch.
Grid [316x1x1] | Block [512x1x1]
[NiftyReg] Exit here. File: /home/qinwang/nifty/niftyreg-git/reg-lib/cuda/resampleKernel.cu:443
`

Then I set `CUDA_NVCC_FLAGS: --maxregcount=32` in the ccmake configure still got this error.
Thanks.

**Comment by mmodat** [comment]
Hi,

I believe this error relate to the grid or block dimension being too large for the card being used. For confirmation, would you be able to run the `devicequery` executable from the CUDA sample?
You can see [on this example](https://gist.github.com/nelson-liu/623eb54d977c98db005eaf2fbc449238) that it specifies `Max dimension size of a thread block (x,y,z)` and `Max dimension size of a grid size (x,y,z)`

Does the process fails from the begining or when reaching the lastest level of the image pyramid?
Would you be able to print the log of the reg_aladin output here?

**Comment by wangqin4377** [comment]
Hi,
I set -maxrregcount=24 in CUDA_NVCC_FLAGS at the ccmake solve this problem.
Thanks
