### ISSUE TITLE
NiftyRegConfig.cmake

### ISSUE THREAD

**Issue by rijobro** [KCL-BMEIS/niftyreg#50]
Would it be possible to create a `NiftyRegConfig.cmake` file during the configure phase? This would be useful for any packages that depend on NiftyReg, such as https://github.com/CCPPETMR/SIRF/, avoiding the use of a more complicated `FindNiftyReg.cmake` file. 

I don't mind doing this if you agree it will be useful.

As a minimum, it only needs to contain:
- path to source
- path to binary
- libraries
- include dir
- version number

It could also contain e.g., CUDA information. However, as I don't need these, I won't be putting them in.

**Comment by mmodat** [comment]
Been merged. Thank you for taking care of that.
