### ISSUE TITLE
Compiling fails on macOS b/c of dynamic library not found

### ISSUE THREAD

**Issue by vigji** [KCL-BMEIS/niftyreg#69]
I have been trying to follow instructions in https://github.com/KCL-BMEIS/niftyreg/wiki/install to compile NiftyReg on a macOS catalina.

I have done everything as required: I have the folders /Users/username/niftyreg_install and build; i enter /Users/username/niftyreg_install in the configuration window; everything runs; and when trying `reg_f3d -h` I get the following error:

```
dyld: Library not loaded: lib_reg_f3d.dylib
  Referenced from: /Users/username/niftyreg_install/bin/reg_f3d
  Reason: image not found
Abort trap: 6
```

Do you have any idea  about what could I be doing wrong?

**Comment by fepegar** [comment]
I added this to my `.bashrc`, not sure if it's needed:
```bash
export NIFTYREG_INSTALL=/Users/fernando/git/niftyreg/install
PATH=${NIFTYREG_INSTALL}/bin:$PATH
LD_LIBRARY_PATH={NIFTYREG_INSTALL}/lib:${LD_LIBRARY_PATH}
export PATH
export LD_LIBRARY_PATH
```

**Comment by vigji** [comment]
Thank for the reply!
Unfortunately, either I am doing something wrong or it does not seem to be working...

**Comment by vigji** [comment]
Ok, I got the problem.
Configuring the .bash_profile with those line solves the problem when running from a shell, but when I try to run commands through python `subprocess.check_call `it does not recognise the configured `LD_LIBRARY_PATH`, I needed to prepend it again in the string with the other commands.
Thanks for the help!
