### ISSUE TITLE
Compiling linking to relative path

### ISSUE THREAD

**Issue by vigji** [KCL-BMEIS/niftyreg#70]
I have a question related to the compilation.
I followed the instruction to compile the binaries on a macOS and everything worked perfectly.
When configuring the compilation, I had to specify the absolute path where to find the `.dyld` files. Is there a way to make this path relative to the `/bin` folder, so that I can move the package around and still looks for them in the correct place? 

(the question is related to add support for macOS in  the niftyreg-based package [amap-python](https://github.com/SainsburyWellcomeCentre/amap-python))

I apologise for the naïveté of the question, but I have 0 experience with compiling and this would be potentially very useful.

**Comment by mmodat** [comment]
amap-python seems to have evolved in regbrain. Closing this for now while I am slowly getting back to it.
