### ISSUE TITLE
reg_f3d -ln option error

### ISSUE THREAD

**Issue by taylorwuselman-zz** [KCL-BMEIS/niftyreg#72]
My research lab has developed Python script utilizing reg_aladin and reg_f3d to perform subsequent linear/non-linear transformations of mouse MR brain image masks to "skull strip" the extraneous brain tissue. I attached the pdf of the paper in case more information is needed about what we are using Nifty Reg for. 

However, when downloading the most recent version of NiftyReg on a Windows 10 laptop using a Linux terminal (Ubuntu app) to apply this code, I consistently get the following error.

_Segmentation fault (core dumped)_

The error occurs on line 57 of the attached Python code (as a .txt; [skullstripper_v2.txt](https://github.com/KCL-BMEIS/niftyreg/files/5008908/skullstripper_v2.txt))  and stems from the _reg_f3d -ln option_, i.e. when ln=0. If ln>0 the code will run, however, our output masks are no longer usable as we do not want to run an optimization for the alignment of a binary mask, we simply want to apply the transform.

Is _ln=0_ not an option in the most recent release of NiftyReg? If so we would like to know so that we can update our code. Or does this stem from something else related to authorized memory allocation on my device; hence the Segmentation Fault error?

[Delora et al. - 2016 - A simple rapid process for semi-automated brain ex.pdf](https://github.com/KCL-BMEIS/niftyreg/files/5008927/Delora.et.al.-.2016.-.A.simple.rapid.process.for.semi-automated.brain.ex.pdf)

**Comment by poppynikou** [comment]
Hey @taylorwuselman I am also having a similar problem, did you manage to find the solution?

**Comment by mmodat** [comment]
`reg_resample` can be use to apply a known transformation without any optimisation. More details about `reg_resample` arguments can be found [here](https://github.com/KCL-BMEIS/niftyreg/wiki/executable#regresample).
