### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by stavrizinonos** [KCL-BMEIS/niftyreg#77]
Is there an example on how to install this package to windows using python? i have found this https://pypi.org/project/NiftyPy/ , but i am not sure how to use it as there are no any examples.
Thank you

**Comment by yamatteo** [comment]
If somebody is looking for the answer, I found help in [here](http://cmictig.cs.ucl.ac.uk/wiki/index.php/NiftyReg_install). In my situation i used cmake and not ccmake because I had to automate the process.

```
cd ~
git clone https://github.com/KCL-BMEIS/niftyreg nifty_source
mkdir ~/nifty_build
cd ~/nifty_build
cmake ~/nifty_source
make
make install
```
