### ISSUE TITLE
niftyreg error

### ISSUE THREAD

**Issue by nightandweather** [KCL-BMEIS/niftyreg#89]
![스크린샷 2022-08-24 오후 3 14 22](https://user-images.githubusercontent.com/48376964/186364822-d3ac1319-5409-46ab-9b86-268922dacf7c.png)
![스크린샷 2022-08-24 오후 5 08 45](https://user-images.githubusercontent.com/48376964/186546315-a61caffd-8d89-4a79-83c7-14a32aefe398.png)

Hi, I'm following niftyreg code and registering in my own dataset.
can i have advice in this situation?

dataset :  160 *160 *160 H/N CT images and organ structure

thank you

**Comment by AXu0511** [comment]
Hello! Have you solved your problem? I met the same question as you did.
