### ISSUE TITLE
Check installed version of niftyreg

### ISSUE THREAD

**Issue by Chad1921** [KCL-BMEIS/niftyreg#91]
Hi,

Is there a command to check the version number of the instralled niftyreg?
Thanks,

Colm

**Comment by mmodat** [comment]
Hi,

Quite dated post but replying in case it helps anyone. All executables have a `--version` flag that prints out the version.
Please see [this page](https://github.com/KCL-BMEIS/niftyreg/wiki/executable) for a list of all commands.
